// Shim for tslib to fix module loading issues
import * as tslib from 'tslib/tslib.es6.js';
export default tslib;
export const __extends = tslib.__extends;
export const __assign = tslib.__assign;
export const __rest = tslib.__rest;
export const __decorate = tslib.__decorate;
export const __param = tslib.__param;
export const __metadata = tslib.__metadata;
export const __awaiter = tslib.__awaiter;
export const __generator = tslib.__generator;
export const __exportStar = tslib.__exportStar;
export const __values = tslib.__values;
export const __read = tslib.__read;
export const __spread = tslib.__spread;
export const __spreadArrays = tslib.__spreadArrays;
export const __spreadArray = tslib.__spreadArray;
export const __await = tslib.__await;
export const __asyncGenerator = tslib.__asyncGenerator;
export const __asyncDelegator = tslib.__asyncDelegator;
export const __asyncValues = tslib.__asyncValues;
export const __makeTemplateObject = tslib.__makeTemplateObject;
export const __importStar = tslib.__importStar;
export const __importDefault = tslib.__importDefault;
export const __classPrivateFieldGet = tslib.__classPrivateFieldGet;
export const __classPrivateFieldSet = tslib.__classPrivateFieldSet;
export const __classPrivateFieldIn = tslib.__classPrivateFieldIn;
export const __createBinding = tslib.__createBinding;
export const __addDisposableResource = tslib.__addDisposableResource;
export const __disposeResources = tslib.__disposeResources;
export const __rewriteRelativeImportExtension = tslib.__rewriteRelativeImportExtension;
